region:

function_name: pylambda 
handler: service.handler
description: lambda-uploader
runtime: python3.7
role: role-lambda-upload

bucket_name: ''
s3_key_prefix: ''

aws_access_key_id: 
aws_secret_access_key: 

# dist_directory: dist
timeout: 900
memory_size: 1024
concurrency: 1


# Experimental Environment variables
#environment_variables:
#    env_1: foo
#    env_2: baz

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
